BEGIN;

DROP SCHEMA IF EXISTS warehouse CASCADE;
CREATE SCHEMA warehouse;
SET search_path TO warehouse, public;

CREATE TABLE dim_date (
    date_key         INTEGER PRIMARY KEY,
    full_date        DATE UNIQUE,
    day_of_month     SMALLINT,
    month_number     SMALLINT,
    month_name       TEXT,
    quarter_number   SMALLINT,
    year             SMALLINT,
    CONSTRAINT dim_date_key_ck CHECK (date_key >= 0),
    CONSTRAINT dim_date_month_ck CHECK (month_number IS NULL OR month_number BETWEEN 1 AND 12),
    CONSTRAINT dim_date_quarter_ck CHECK (quarter_number IS NULL OR quarter_number BETWEEN 1 AND 4)
);

CREATE TABLE dim_source (
    source_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        TEXT UNIQUE,
    display_name     TEXT,
    source_type      TEXT,
    issn_l           TEXT,
    issn             TEXT,
    publisher        TEXT
);

CREATE TABLE dim_work_type (
    work_type_key    SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_type        TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_topic (
    topic_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id         TEXT NOT NULL UNIQUE,
    display_name     TEXT NOT NULL,
    subfield_id      TEXT,
    subfield_name    TEXT,
    field_id         TEXT,
    field_name       TEXT,
    domain_id        TEXT,
    domain_name      TEXT
);

CREATE TABLE dim_author (
    author_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id        TEXT NOT NULL UNIQUE,
    display_name     TEXT
);

CREATE TABLE dim_institution (
    institution_key  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id   TEXT NOT NULL UNIQUE,
    display_name     TEXT,
    country_code     CHAR(2),
    institution_type TEXT
);

-- Grain: one retained OpenAlex work. publication_year is retained as a degenerate
-- dimension so a work with an unknown publication date remains reportable by year.
CREATE TABLE fact_work (
    work_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id           TEXT NOT NULL UNIQUE,
    date_key          INTEGER NOT NULL REFERENCES dim_date (date_key),
    source_key        BIGINT NOT NULL REFERENCES dim_source (source_key),
    work_type_key     SMALLINT NOT NULL REFERENCES dim_work_type (work_type_key),
    publication_year  SMALLINT,
    cited_by_count    INTEGER NOT NULL,
    publication_count SMALLINT NOT NULL DEFAULT 1,
    is_oa             BOOLEAN,
    oa_status         TEXT,
    CONSTRAINT fact_work_citations_ck CHECK (cited_by_count >= 0),
    CONSTRAINT fact_work_publication_count_ck CHECK (publication_count = 1)
);

-- Full association contribution is intentional: sums through these bridges may
-- exceed work-level totals when a work has multiple related dimension members.
CREATE TABLE bridge_work_topic (
    work_key          BIGINT NOT NULL REFERENCES fact_work (work_key),
    topic_key         BIGINT NOT NULL REFERENCES dim_topic (topic_key),
    topic_score       NUMERIC(7,6),
    is_primary_topic  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (work_key, topic_key),
    CONSTRAINT bridge_topic_score_ck CHECK (topic_score IS NULL OR topic_score BETWEEN 0 AND 1)
);

CREATE TABLE bridge_work_author (
    work_key          BIGINT NOT NULL REFERENCES fact_work (work_key),
    author_key        BIGINT NOT NULL REFERENCES dim_author (author_key),
    author_position   TEXT,
    author_order      INTEGER NOT NULL,
    is_corresponding  BOOLEAN,
    PRIMARY KEY (work_key, author_key),
    CONSTRAINT bridge_author_order_ck CHECK (author_order >= 1)
);

CREATE TABLE bridge_work_institution (
    work_key          BIGINT NOT NULL REFERENCES fact_work (work_key),
    institution_key   BIGINT NOT NULL REFERENCES dim_institution (institution_key),
    PRIMARY KEY (work_key, institution_key)
);

-- Factless relationship bridge retained to support the relational citation-path
-- prototype; it is not used for standard OLAP aggregates.
CREATE TABLE bridge_work_citation (
    citing_work_key BIGINT NOT NULL REFERENCES fact_work (work_key),
    cited_work_key  BIGINT NOT NULL REFERENCES fact_work (work_key),
    PRIMARY KEY (citing_work_key, cited_work_key),
    CONSTRAINT bridge_citation_no_self_loop_ck CHECK (citing_work_key <> cited_work_key)
);

COMMIT;
